version: '3'

services:

  contracts:
    build:
      context: ./contracts
    # restart: always
    ports:
      - 8545:8545

  frontend:
    build:
      context: ./frontend
    # restart: always
    ports:
      - 3000:3000

  cog:
    build:
      context: ./contracts/lib/cog/services
    restart: always
    entrypoint:
    - /bin/ash
    - -eu
    - -c
    - |
      echo "waiting"
      /wait-for -it contracts:8545 -t 300
      echo "starting"
      exec /ds-node
    environment:
      CHAIN_ID: "1337"
      SEQUENCER_PRIVATE_KEY: "095a37ef5b5d87db7fe50551725cb64804c8c554868d3d729c0dd17f0e664c87"
      SEQUENCER_PROVIDER_URL_HTTP: "http://contracts:8545"
      SEQUENCER_PROVIDER_URL_WS: "ws://contracts:8545"
      INDEXER_WATCH_PENDING: "false"
      INDEXER_PROVIDER_URL_HTTP: "http://contracts:8545"
      INDEXER_PROVIDER_URL_WS: "ws://contracts:8545"
    ports:
      - 8080:8080
    depends_on:
      - contracts


