version: '3'

services:

  ###############################################################################
  #                                                                             #
  # nightly profile                                                             #
  #                                                                             #
  # run via:                                                                    #
  #                                                                             #
  #     > docker-compose --profile=nightly up --pull=always                     #
  #                                                                             #
  # this provisions a local chain and api backend from the most recent build.   #
  #                                                                             #
  # useful for: artists, developing just the unity client, testing latest build #
  #                                                                             #

  ds-contracts-nightly:
    profiles: ["nightly"]
    image: ghcr.io/playmint/ds-contracts:latest
    pull_policy: always
    restart: always
    platform: linux/amd64
    ports:
      - 3045:8545
  cog-services-nightly:
    profiles: ["nightly"]
    image: ghcr.io/playmint/cog-services:latest
    pull_policy: always
    restart: always
    entrypoint:
    - /bin/ash
    - -eu
    - -c
    - |
      echo "waiting"
      /wait-for -it ds-contracts-nightly:8545 -t 300
      echo "starting"
      exec /ds-node
    environment:
      CHAIN_ID: "1337"
      SEQUENCER_PRIVATE_KEY: "095a37ef5b5d87db7fe50551725cb64804c8c554868d3d729c0dd17f0e664c87"
      SEQUENCER_PROVIDER_URL_HTTP: "http://ds-contracts-nightly:8545"
      SEQUENCER_PROVIDER_URL_WS: "ws://ds-contracts-nightly:8545"
      INDEXER_WATCH_PENDING: "false"
      INDEXER_PROVIDER_URL_HTTP: "http://ds-contracts-nightly:8545"
      INDEXER_PROVIDER_URL_WS: "ws://ds-contracts-nightly:8545"
    ports:
      - 3080:8080
    depends_on:
      - ds-contracts-nightly
  #                                                                              #
  #                                                                              #
  ################################################################################






  ################################################################################
  #                                                                              #
  # dev profile                                                                  #
  #                                                                              #
  # run via:                                                                     #
  #                                                                              #
  #     > docker-compose --profile=dev up --abort-on-container-exit --build      #
  #                                                                              #
  # this provisions a local chain and api backend FROM SOURCE.                   #
  #                                                                              #
  # you must have the ds-uinity, ds-contracts, and cog-services repositories     #
  # checked out as sibling directories next to each other and checked out at the #
  # versions you want to provision.                                              #
  #                                                                              #

  ds-contracts-dev:
    profiles: ["dev"]
    restart: always
    platform: linux/amd64
    build:
      context: ../ds-contracts
    ports:
      - 3045:8545

  cog-services-dev:
    profiles: ["dev"]
    restart: always
    build:
      context: ../cog-services
    entrypoint:
    - /bin/ash
    - -eu
    - -c
    - |
      echo "waiting"
      /wait-for -it ds-contracts-dev:8545 -t 300
      echo "starting"
      exec /ds-node
    environment:
      CHAIN_ID: "1337"
      SEQUENCER_PRIVATE_KEY: "095a37ef5b5d87db7fe50551725cb64804c8c554868d3d729c0dd17f0e664c87"
      SEQUENCER_PROVIDER_URL_HTTP: "http://ds-contracts-dev:8545"
      SEQUENCER_PROVIDER_URL_WS: "ws://ds-contracts-dev:8545"
      INDEXER_WATCH_PENDING: "false"
      INDEXER_PROVIDER_URL_HTTP: "http://ds-contracts-dev:8545"
      INDEXER_PROVIDER_URL_WS: "ws://ds-contracts-dev:8545"
    ports:
      - 3080:8080
    depends_on:
      - ds-contracts-dev
  #                                                                              #
  #                                                                              #
  ################################################################################


