name: Deployment (exp)

on:
  workflow_dispatch:

jobs:

  build:
    name: Exp Build
    uses: ./.github/workflows/build.yaml
    with:
      DEPLOYMENT_ENVIRONMENT: exp
      DEPLOYMENT_PRIORITY: default
      FRONTEND_IMAGE_NAME: playmint/ds-shell
      CONTRACTS_IMAGE_NAME: playmint/ds-contracts
      SERVICES_IMAGE_NAME: playmint/ds-services
      PLATFORMS: linux/amd64
      AZURE_FRONT_DOOR_PURGE: false
    secrets:
      AZURE_REGISTRY_URL: ${{ secrets.AZURE_REGISTRY_URL }}
      AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CLUSTER_NAME: ${{ secrets.AZURE_CLUSTER_NAME }}
      AZURE_CLUSTER_RESOURCE_GROUP: ${{ secrets.AZURE_CLUSTER_RESOURCE_GROUP }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
