name: check-frontend

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Configure nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.x
      - name: Install
        run: |
          npm ci
          (cd core && npm run build)
      - name: Lint
        working-directory: frontend
        run: |
          npx next lint --max-warnings=0
      - name: Format
        working-directory: frontend
        run: |
          npx eslint . --ext .ts --ext .tsx --quiet
      - name: Build
        working-directory: frontend
        run: |
          npx next build
